### ISSUE TITLE
scikit learn installation issue

### ISSUE THREAD

**Issue by Jaswanth-12** [scikit-learn/sklearn-pypi-package#11]
when i run this pip install sklearn  it is showing can anybody help me how to resolve
Collecting sklearn
  Using cached sklearn-0.0.post7.tar.gz (3.6 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

      https://github.com/scikit-learn/sklearn-pypi-package/issues/new
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by adrinjalali** [comment]
You should be installing the package as `pip install scikit-learn` and not as `pip install sklearn`
