### ISSUE TITLE
error with sklearn

### ISSUE THREAD

**Issue by Taliver80** [scikit-learn/sklearn-pypi-package#14]
625.6   Downloading sklearn-0.0.post7.tar.gz (3.6 kB)
626.3     ERROR: Command errored out with exit status 1:
626.3      command: /opt/conda/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-2vg6w2_d/sklearn/setup.py'"'"'; __file__='"'"'/tmp/pip-install-2vg6w2_d/skle
arn/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --eg
g-base /tmp/pip-install-2vg6w2_d/sklearn/pip-egg-info
626.3          cwd: /tmp/pip-install-2vg6w2_d/sklearn/

i had this problem . can you help ?

**Comment by lesteve** [comment]
I am afraid there is not enough information in your post to be able to help.

If you have not already I invite you to read [this](https://github.com/scikit-learn/sklearn-pypi-package#how-to-fix-the-error-for-the-main-use-cases) about how to fix the errors in the main use cases.

If you still have this issue, please post the full error message as well as with more context as what you are trying to do!
