### ISSUE TITLE
Error installing sklearn via cmd

### ISSUE THREAD

**Issue by Idoma-developer** [scikit-learn/sklearn-pypi-package#15]
I am trying to install sklearn for my data analysis project, but I'm getting this error  error: ![CMD](https://github.com/scikit-learn/sklearn-pypi-package/assets/24852166/e79134aa-92f7-4952-80a1-f7ec9353f978)-exited-with-error.

**Comment by hugovk** [comment]
As the text says, please use scikit-learn instead of sklearn.
