### ISSUE TITLE
python -m pip install refy

### ISSUE THREAD

**Issue by imran131399** [scikit-learn/sklearn-pypi-package#27]
Collecting myterial (from refy==1.0.0.8)
  Using cached myterial-1.2.1-py3-none-any.whl (6.3 kB)
Collecting rich (from refy==1.0.0.8)
  Using cached rich-13.6.0-py3-none-any.whl.metadata (18 kB)
Collecting bibtexparser (from refy==1.0.0.8)
  Using cached bibtexparser-1.4.1.tar.gz (55 kB)
  Preparing metadata (setup.py) ... done
Collecting xmltodict (from refy==1.0.0.8)
  Using cached xmltodict-0.13.0-py2.py3-none-any.whl (10.0 kB)
Collecting sklearn (from refy==1.0.0.8)
  Using cached sklearn-0.0.post11.tar.gz (3.6 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
      rather than 'sklearn' for pip commands.

      Here is how to fix this error in the main use cases:
      - use 'pip install scikit-learn' rather than 'pip install sklearn'
      - replace 'sklearn' by 'scikit-learn' in your pip requirements files
        (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)

**Comment by jjerphan** [comment]
Thank you for the report.

This is a problem with [`FedeClaudi/refy` which currently depends on `sklearn`](https://github.com/FedeClaudi/refy/blob/f39197c42528b5a9ce300d4aeb29c3710c370692/setup.py#L17) instead of `scikit-learn`.

Feel free to report an issue on refy's issue tracker.

**Comment by Devilelal** [comment]
Already installed scikit-learn 
But still that problem

**Comment by imran131399** [comment]
Already installed scikit-learn
But still that problem

**Comment by ogrisel** [comment]
@Devilelal and @imran131399: the problem is not about installing `scikit-learn` but about replacing the browned out `sklearn` alias dependency by the correct `scikit-learn` dependency in the metadata of the `refy` package.

It's up to the maintainers of the `refy` project to fix this problem. Please open an issue on their tracker if none was already opened.

**Comment by ogrisel** [comment]
I went ahead an created the PR myself: https://github.com/FedeClaudi/refy/pull/6
