### ISSUE TITLE
installing sklearn instead of scikit-learn in preety_confusion_matrix

### ISSUE THREAD

**Issue by amandeepraj** [scikit-learn/sklearn-pypi-package#32]
when trying to install preety_confusion_matrix, every other components installed sucessfully , but sklearn failed collecting metadata

 Collecting sklearn<0.1,>=0.0 (from pretty_confusion_matrix)
  Downloading sklearn-0.0.post12.tar.gz (2.6 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'

i think it should be scikit-learn instead of sklearn

**Comment by adrinjalali** [comment]
That's an issue with the `pretty-confusion-matrix` library, you can open an issue on their side, they need to fix their dependency:

https://github.com/wcipriano/pretty-print-confusion-matrix/blob/master/pyproject.toml#L17C3-L17C3
