### ISSUE TITLE
still error occured

### ISSUE THREAD

**Issue by rahulit-netizen** [scikit-learn/sklearn-pypi-package#33]
# Let's split the data into X_train, X_test, y_train and y_test
# We will use X_train and y_train to train the model and X_test and y_test to test the model
from scikit-learn_selecting import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15, random_state=2)

**Comment by adrinjalali** [comment]
That is not valid python code. You should do `pip install scikit-learn` instead of `pip install sklearn`, and if you use a library that depends on `sklearn` instead of `scikit-learn`, you should tell them to fix it.
