### ISSUE TITLE
sklearn issue

### ISSUE THREAD

**Issue by shruti-124** [scikit-learn/sklearn-pypi-package#34]
ImportError                               Traceback (most recent call last)
Cell In[22], line 1
----> 1 from sklearn.linear_model import linearRegression

ImportError: cannot import name 'linearRegression' from 'sklearn.linear_model' (C:\Users\shrut\anaconda3\Lib\site-packages\sklearn\linear_model\__init__.py)

**Comment by lesteve** [comment]
This does not seem to be related to the `sklearn` package.

Unfortunately we don't have the bandwidth to answer this kind of general Python questions, I would encourage you to find someone around you that can help you or ask on generic Q&A forums like StackOverflow, good luck!
