### ISSUE TITLE
Import mlrose  issue

### ISSUE THREAD

**Issue by sudhir8591** [scikit-learn/sklearn-pypi-package#44]
Tried  to import mlrose but throwing error "ModuleNotFoundError: No module named 'mlrose'

Tired all the permutations and combinations nothing works out.

1. SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True
2. By PIP install PyCaret 
3. As per Kaggle tried        pip install scikit.learn==0.22

Nothing works out please help me to solve this issue ASAP
If 
Import mlrose
works find then all the issues will be solved.

**Comment by lesteve** [comment]
Same issue as https://github.com/scikit-learn/sklearn-pypi-package/issues/42, this is a mlrose issue.

**Comment by lesteve** [comment]
I added some details in https://github.com/scikit-learn/sklearn-pypi-package/issues/42#issuecomment-2133388938 as work-arounds that should work by setting the `SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL` environment variable.
