### ISSUE TITLE
import

### ISSUE THREAD

**Issue by J1R429** [scikit-learn/sklearn-pypi-package#45]
com a mudança do nome, como realiza o import? no jupyter dá erro o - do nome
![Captura de tela 2024-06-05 224404](https://github.com/scikit-learn/sklearn-pypi-package/assets/123896356/0f0ec8dd-ea01-41cf-a301-420c28a4dbd0)

**Comment by jjerphan** [comment]
Hola,

El módulo de Python que hay que importar es `sklearn`:

```python
import sklearn
```

Para empezar, recomiendo [esta sección de la documentación](https://scikit-learn.org/stable/getting_started.html).
