### ISSUE TITLE
ImportError    Traceback (most recent call last)

### ISSUE THREAD

**Issue by LEGEND7106** [scikit-learn/sklearn-pypi-package#46]
Cell In[5], line 5
       from sklearn.tree import DecisionTreeClassifier
      
---->  from sklearn.externals import joblib

       music_data = pd.read_csv("music.csv")
       X = music_data.drop(columns = ["genre"])

ImportError: cannot import name 'joblib' from 'sklearn.externals' (C:\Users\USER\anaconda3\Lib\site-packages\sklearn\externals\__init__.py)

**Comment by LEGEND7106** [comment]
Please i need help to solve this error

**Comment by adrinjalali** [comment]
Joblib is a separate package, import that directly.
