### ISSUE TITLE
sklearn package support

### ISSUE THREAD

**Issue by Javedbyte** [scikit-learn/sklearn-pypi-package#49]
Function 'plt_overfit.py' has dependency for 'sklearn' package in one of Python project due to which 'ModuleNotFoundError' is received.  How to handle it? However, I understand the 'sklearn' package has been deprecated and instead recommended to use 'scikit-learn'. I am not sure the suggested package supports module definition such as 'LogisticRegression, Ridge' etc. ?

**Comment by adrinjalali** [comment]
sklearn was an alias for `scikit-learn`, you should just replace your install scripts to install `scikit-learn` directly.

**Comment by Javedbyte** [comment]
Thanks, it worked by installing scikit-learn rather than sklearn
