### ISSUE TITLE
error: subprocess-exited-with-error

### ISSUE THREAD

**Issue by pcr08** [scikit-learn/sklearn-pypi-package#52]
Hi,
I am trying to install a package that has dependencies on sklearn, and when installing it, I get this error because the package is deprecated. I would like to ask for some help, as I don't know how to fix it. I have tried to write on the terminal "set  SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True" but I still get the error.
![image](https://github.com/user-attachments/assets/964a5f7b-ddfb-45d3-8072-7eaf207ad7a4)

Thanks!

**Comment by adrinjalali** [comment]
Depending on your shell, there might be different ways to set the env variable. Other than that, you need to contact the package maintainers for a fix.
