### ISSUE TITLE
about python running module

### ISSUE THREAD

**Issue by Abhiyerra123** [scikit-learn/sklearn-pypi-package#54]
how to replace sklearn files to scirict-learn requried files in command prompt for python 3.13.0

**Comment by Abhiyerra123** [comment]
File "C:/Users/LENOVO/AppData/Local/Programs/Python/Python313/exp1.py", line 1, in <module>
    from sklearn.linear_model import LinearRegression
ModuleNotFoundError: No module named 'sklearn'
how to solve this issue

**Comment by adrinjalali** [comment]
You need to have `scikit-learn` as a package installed in your environment.
