### ISSUE TITLE
not able to install sklearn

### ISSUE THREAD

**Issue by mirzabilalbaig123** [scikit-learn/sklearn-pypi-package#8]
note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by hugovk** [comment]
What did you try to install exactly, and how? Please include the full traceback. 

Also the general advice is to switch from sklearn to scikit-learn.

**Comment by adrinjalali** [comment]
Closing as no feedback has come from the OP. Happy to reopen if more info is given.
